# Generated by Django 6.0.2 on 2026-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('sku', models.CharField(help_text='Unikátní identifikátor produktu (Stock Keeping Unit)', max_length=50, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(help_text='SHA-256 hash kanonické JSON reprezentace produktu', max_length=64)),
                ('last_synced', models.DateTimeField(help_text='Časové razítko poslední úspěšné synchronizace')),
                ('synced', models.BooleanField(default=False, help_text='Příznak, zda byl produkt úspěšně synchronizován')),
            ],
            options={
                'verbose_name': 'Sync Record',
                'verbose_name_plural': 'Sync Records',
                'db_table': 'integrator_syncrecord',
            },
        ),
    ]
